# Generated by Django 4.2.6 on 2023-11-20 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0046_merge_20230913_1545"),
        ("scanpipe", "0047_discoveredpackage_scanpipe_di_version_44de05_idx"),
    ]

    operations = []
