# Generated by Django 4.2.6 on 2024-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0048_merge_20231120_2034"),
    ]

    operations = [
        migrations.CreateModel(
            name="VulnerablePaths",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repository_id", models.IntegerField()),
                ("path", models.JSONField()),
                ("action_item", models.IntegerField()),
                ("action_type", models.IntegerField()),
            ],
        ),
    ]
