# Generated by Django 4.2.6 on 2024-07-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0049_vulnerablepaths"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnerablepaths",
            name="project_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
