# Generated by Django 4.2.6 on 2024-07-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0050_vulnerablepaths_project_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vulnerablepaths",
            name="action_type",
        ),
        migrations.AddField(
            model_name="vulnerablepaths",
            name="has_commons_in_path",
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
