# Generated by Django 4.2.6 on 2024-07-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0051_remove_vulnerablepaths_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnerablepaths",
            name="vulnerable_package_id",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
