# Generated by Django 4.2.6 on 2024-07-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0052_vulnerablepaths_vulnerable_package_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vulnerablepaths",
            name="action_item",
            field=models.IntegerField(null=True),
        ),
    ]
