# Generated by Django 4.2.6 on 2024-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0055_accounts_companypackages_deploymentcheckpoints_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnerablepaths",
            name="environment",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="vulnerablepaths",
            name="wasp_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
