# Generated by Django 4.2.6 on 2024-07-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0056_vulnerablepaths_environment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vulnerablepaths",
            name="action_item",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
