# Generated by Django 5.0.7 on 2024-08-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0057_alter_vulnerablepaths_action_item"),
        ("scanpipe", "0067_discoveredpackage_notes"),
    ]

    operations = []
